ALTER TABLE combos ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE combos ADD COLUMN IF NOT EXISTS badge VARCHAR(100) DEFAULT 'combo';
ALTER TABLE combos ADD COLUMN IF NOT EXISTS price NUMERIC(10, 2);
ALTER TABLE combos ADD COLUMN IF NOT EXISTS original_price NUMERIC(10, 2);
ALTER TABLE combos ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE combos ADD COLUMN IF NOT EXISTS image_url TEXT;

CREATE TABLE IF NOT EXISTS combo_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  combo_id UUID REFERENCES combos(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
